config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  get 'home/index'

  # devise_for :users
  devise_for :users, controllers: { registrations: 'registrations' , sessions: 'sessions' }

  # Add the following route for signing out
  delete '/sign_out', to: 'sessions#destroy', as: :custom_destroy_user_session

  devise_scope :user do
    get 'login', to: 'devise/sessions#new', as: :custom_login
    post 'login', to: 'devise/sessions#create', as: :custom_user_session
  
    get 'registration', to: 'devise/registrations#new', as: :custom_registration
    post 'registration', to: 'devise/registrations#create', as: :custom_user_registration
  end

  
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :create, :new, :destroy] do 
      resources :comments, only: [:create, :new, :destroy]
      post 'like', on: :member
    end  
 end

 namespace :api do
  resources :users, only: [] do
    resources :posts, only: [:index] do
      resources :comments, only: [:index, :create]
    end
  end
end

 



 root 'home#index'

 


  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, class_name: 'Post', foreign_key: :author_id
  has_many :comments, class_name: 'Comment', foreign_key: :author_id
  has_many :likes, class_name: 'Like', foreign_key: :author_id
  validates :name, presence: true
  validates :photo, presence: true
  validates :bio, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  after_create :generate_api_key

  def admin?
    role == 'admin'
  end

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  private

  def generate_api_key
    api_key = loop do
      generated_api_key = SecureRandom.urlsafe_base64
      break generated_api_key unless User.exists?(api_key: generated_api_key)
    end

    update(api_key:)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'standard'
  before_action :authenticate_user!

  def index
    @user = current_user
    @users = User.all
  end

  def show
    if params[:id] == 'sign_out'
      sign_out(current_user)
      redirect_to root_path, notice: 'You have been signed out successfully.'
    else
      @current_user = current_user
      @user = User.find(params[:id])
      @first_three_posts = @user.posts.limit(3)
      @recent_posts = @user.recent_posts
    end
  end
end

app/views/users/_user.html.erb
<div class = 'user'>
<div class = "image-placeholder"><img src="<%= user.photo %>" alt="Profile Picture"></div>

<div class = 'user-block'>
  <li><h3><%= link_to user.name, user_path(user) %></h3></li>
   <p > Number of posts: <%= user.posts.count%> </p>
 </div>
</div>

app/views/users/index.html.erb
<h2>The list of users</h2>
<p> current user : <%= @user.email%> </p>

<div class = 'user-content'> 

<% @users.each do |user|%>
<%= render partial: 'user', locals: { user: user } %>


<%end%>


</div>

app/views/users/show.html.erb
<h2> User name with posts </h2>

<div class = 'user-content'> 
<div class = 'user'>
<div class = "image-placeholder"><img src="<%= @user.photo %>" alt="Profile Picture"></div>

<div class = 'user-block'>
 <h3><%= @user.name %></h3>
   <p > Number of posts: <%= @user.posts.count%> </p>
 </div>
</div>
 <div class ='user-bio'>
 <p><strong>Bio </strong> </p>
 <p> <%= @user.bio %> </p>
  </div>
  <div class = 'posts-content'>
     <% @first_three_posts.each do |post|%>
   <%= render partial: 'posts/post', locals: { post: post } %>
     <%end%>
   </div>

   <button> <%= link_to 'See all posts', user_posts_path(@user) %> </button>
<div>