config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  get 'home/index'

  # devise_for :users
  devise_for :users, controllers: { registrations: 'registrations' , sessions: 'sessions' }

  # Add the following route for signing out
  delete '/sign_out', to: 'sessions#destroy', as: :custom_destroy_user_session

  devise_scope :user do
    get 'login', to: 'devise/sessions#new', as: :custom_login
    post 'login', to: 'devise/sessions#create', as: :custom_user_session
  
    get 'registration', to: 'devise/registrations#new', as: :custom_registration
    post 'registration', to: 'devise/registrations#create', as: :custom_user_registration
  end

  
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :create, :new, :destroy] do 
      resources :comments, only: [:create, :new, :destroy]
      post 'like', on: :member
    end  
 end

 namespace :api do
  resources :users, only: [] do
    resources :posts, only: [:index] do
      resources :comments, only: [:index, :create]
    end
  end
end

 



 root 'home#index'

 


  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'standard'
  def index
    @user = current_user
    return unless @user.admin? == false && @user.name == 'admin'

    @user.role = 'admin'
    @user.save
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Welcome to My App</h1>

<% if user_signed_in? %>
<!-- User is authenticated -->
  <p>You are logged in as <%= current_user.name %> with the email : <%= current_user.email%></p>
  <p> the current user is <% if current_user.admin? %>an admin <%else%> a user <%end%> </P>
  <!-- Add more content for authenticated users -->
  <div><%= link_to 'Go List of users', users_path %> </div>
 <div> <%= link_to 'Go to Profile', user_path(current_user) %></div>

<% else %>
<!-- User is not authenticated -->
  <p>You are not logged in.</p>
  <p>Only authenticated users can see the content of this page.</p>
  <p>Click here to <%= link_to 'Login', custom_login_path %>.</p>
  <p>Click here to <%= link_to 'Register', custom_registration_path %>.</p>
  <!-- Add more content for non-authenticated users -->

<% end %>