config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  get 'home/index'

  # devise_for :users
  devise_for :users, controllers: { registrations: 'registrations' , sessions: 'sessions' }

  # Add the following route for signing out
  delete '/sign_out', to: 'sessions#destroy', as: :custom_destroy_user_session

  devise_scope :user do
    get 'login', to: 'devise/sessions#new', as: :custom_login
    post 'login', to: 'devise/sessions#create', as: :custom_user_session
  
    get 'registration', to: 'devise/registrations#new', as: :custom_registration
    post 'registration', to: 'devise/registrations#create', as: :custom_user_registration
  end

  
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :create, :new, :destroy] do 
      resources :comments, only: [:create, :new, :destroy]
      post 'like', on: :member
    end  
 end

 namespace :api do
  resources :users, only: [] do
    resources :posts, only: [:index] do
      resources :comments, only: [:index, :create]
    end
  end
end

 



 root 'home#index'

 


  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :comments, class_name: 'Comment', foreign_key: :post_id
  has_many :likes, class_name: 'Like', foreign_key: :post_id

  validates :title, presence: true, length: { maximum: 250 }
  validates :text, presence: true
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counters, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_create :update_user_posts_counter

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  def update_user_posts_counter
    author.increment!(:posts_counter)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  protect_from_forgery with: :null_session
  skip_before_action :authenticate_user!

  def index
    user = User.find(params[:user_id])
    posts = user.posts
    render json: posts
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  layout 'standard'
  before_action :authenticate_user!

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
    @current_user = current_user
  end

  def show
    @post = Post.find(params[:id])
    @user = User.find(params[:user_id])
    @current_user = current_user
  end

  def new
    @post = Post.new
  end

  def like
    @post = Post.find(params[:id])
    @user = current_user
    @like = Like.new(author_id: current_user.id, post_id: @post.id)
    @user_id = params[:user_id]
    @like.save
    redirect_to user_post_path(user_id: @user_id, id: params[:id])
  end

  def destroy
    @post = Post.find(params[:id])

    # Destroy all comments
    @post.comments.destroy_all if @post.comments.exists?
    # Destroy all likes
    @post.likes.destroy_all if @post.likes.exists?

    @post.destroy
    redirect_to user_posts_path(id: current_user.id)
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    @post.comments_counter = 0
    @post.likes_counters = 0

    if @post.save
      redirect_to user_posts_path, notice: 'Post created successfully'
    else
      render 'new'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/views/posts/_comment.html.erb
      <p> <strong><%= comment.author.name%> :</strong> <%= comment.text%> 
      <% if can?(:destroy, comment)%> 
      <%= form_with(model: comment,method: :delete, url: user_post_comment_path(user_id: comment.author_id,post_id: comment.post_id, id: comment.id )) do |form|%>
      <%= form.submit "Delete", class:'submit' %>
      <%end%>
      <% end %> 
      </p>

app/views/posts/_post.html.erb
<div class='post-content'> 
  <li>
    <h4><%= link_to post.title, user_post_path(user_id: @user.id, id: post.id) %></h4>
  </li>
  <p><%= post.text %></p>
  <% if can?(:destroy, post) %>
    <div>
      <%= form_with(model: post, method: :delete, url: user_post_path(user_id: @user.id, id: post.id)) do |form| %>
        <%= form.submit "Delete" %>
      <% end %> 
    </div>
  <% end %>
  <p class='counters'>
    Comments: <%= post.comments_counter.to_i > 0 ? post.comments_counter : '0' %> Likes: <%= post.likes_counters.to_i > 0 ? post.likes_counters : '0' %>
  </p>
</div>

app/views/posts/index.html.erb
<h2> list of all posts and comment of a user </h2>

<div class = 'user-content'> 
<div class = 'user'>
<div class = "image-placeholder"><img src="<%= @user.photo %>" alt="Profile Picture"></div>

<div class = 'user-block'>
 <h3><%= @user.name %></h3>
   <p > Number of posts: <%= @user.posts.count%> </p>
 </div>
 </div>

<div class='posts-content'>
  <button><%= link_to 'Add new Post', new_user_post_path(@current_user) %></button>
  <% @posts.each do |post| %>
    <div class='user-post'>
      <%= render partial: 'post', locals: { post: post } %>
      <div class='comments-content'>
        <p><strong>Comments:</strong></p>
        <% post.comments.each do |comment| %>
        <div class='comment_content'>
          <%= render partial: 'comment', locals: { comment: comment } %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<button>Pagination</button>

app/views/posts/new.html.erb
<h2> New post </h2>
<%= form_with(model:  @post, url: user_posts_path, local: true) do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>

  <%= form.label :text, 'content' %>
  <%= form.text_area :text %>
  

  <%= form.submit "Create Post" %>
<% end %>

app/views/posts/show.html.erb
<h2> details of a post </h2>
<div class = 'user-post'>
     <div class = 'post-content'> 
   <p class = 'post'>  <strong> <%= @post.title %> </strong>      <span class = 'counters'> Comments: <%= @post.comments_counter.to_i > 0 ? @post.comments_counter : '0'  %> Likes: <%= @post.likes_counters.to_i > 0 ? @post.likes_counters : '0'%>  </span> 
    </p>
     <p> <%= @post.text%> </p>
     <div class = 'post_buttons'> <%= form_with(model: @post, url: like_user_post_path(user_id: @user.id, id: @post.id), method: :post, local: true) do |form| %>
  <%= form.button type: :submit, class: 'like-button' do %>
    Add Like
  <% end %>
<% end %> 
 <% if can?(:destroy, @post) %>
  <%= form_with(model: @post, method: :delete, url: user_post_path(user_id: @user.id, id: @post.id)) do |form| %>
        <%= form.submit "Delete", class:"submit" %>
      <% end %> 
  <% end %></div>
 
     </div>
     <div class='comments-content'>
     <p><strong> Comments :</strong> </p>
     <% @post.comments.each do |comment|%>
     <div class = 'comment_content'>
      <%= render partial: 'comment', locals: { comment: comment } %>
     </div>
     <%end%>
     </div>
     </div>

     <button> <%= link_to 'Add Comment', new_user_post_comment_path(user_id: @current_user.id, post_id: @post.id) %> </button>
     </div>

     